config/routes.rb
require 'subscribem/constraints/subdomain_required'

Subscribem::Engine.routes.draw do
  constraints(Subscribem::Constraints::SubdomainRequired) do
    scope module: 'account' do
      root to: 'dashboard#index', as: :account_root
      get  '/sign_in', to: 'sessions#new',    as: :sign_in
      post '/sign_in', to: 'sessions#create', as: :sessions
    end
  end

  get 'accounts/new'

  root 'dashboard#index'
  get '/sign_up', to: 'accounts#new', as: :sign_up
  post '/accounts', to: 'accounts#create', as: :accounts
end

app/models/subscribem/account.rb
module Subscribem
  class Account < ActiveRecord::Base
    EXCLUDED_SUBDOMAINS = %w(admin)

    before_validation { self.subdomain = subdomain.to_s.downcase }

    validates :subdomain, presence: true, uniqueness: true
    validates_exclusion_of :subdomain, in: EXCLUDED_SUBDOMAINS,
      message: 'is not allowed. Please choose another subdomain.'
    validates_format_of :subdomain, with: /\A[\w\-]+\Z/i,
      message: 'is not allowed. Please choose another subdomain.'

    belongs_to :owner, class_name: 'Subscribem::User'
    has_many :members, class_name: 'Subscribem::Member'
    has_many :users, through: :members
    accepts_nested_attributes_for :owner

    def self.create_with_owner(params={})
      account = new(params)
      if account.save
        account.users << account.owner
      end
      account
    end

  end
end

app/models/subscribem/member.rb
module Subscribem
  class Member < ActiveRecord::Base
    belongs_to :account, class_name: 'Subscribem::Account'
    belongs_to :user, class_name: 'Subscribem::User'
  end
end

app/models/subscribem/user.rb
module Subscribem
  class User < ActiveRecord::Base
    has_secure_password
  end
end

app/controllers/subscribem/account/dashboard_controller.rb
require_dependency "subscribem/application_controller"

module Subscribem
  class Account::DashboardController < Subscribem::ApplicationController
    before_action :authenticate_user!
  end
end

app/controllers/subscribem/account/sessions_controller.rb
require_dependency "subscribem/application_controller"

module Subscribem
  class Account::SessionsController < Subscribem::ApplicationController
    def new
      @user = User.new
    end

    def create
      if env['warden'].authenticate(scope: :user)
        flash[:notice] = 'You are now signed in.'
        redirect_to root_path
      else
        @user = User.new
        flash[:error] = 'Invalid email or password.'
        render :new
      end
    end
  end
end

app/controllers/subscribem/accounts_controller.rb
require_dependency "subscribem/application_controller"

module Subscribem
  class AccountsController < ApplicationController
    def new
      @account = Subscribem::Account.new
      @account.build_owner
    end

    def create
      @account = Subscribem::Account.create_with_owner(account_params)
      if @account.save
        env['warden'].set_user(@account.owner, scope: :user)
        env['warden'].set_user(@account, scope: :account)
        flash[:success] = 'Your account has been successfully created.'
        redirect_to subscribem.root_url(subdomain: @account.subdomain)
      else
        flash[:error] = 'Sorry, your account could not be created.'
        render :new
      end
    end

    private

    def account_params
      params.require(:account).permit(:name, :subdomain,
        { owner_attributes: [:email, :password, :password_confirmation] })
    end
  end
end

app/controllers/subscribem/application_controller.rb
module Subscribem
  class ApplicationController < ActionController::Base

    def current_account
      if user_signed_in?
        @current_account ||= env['warden'].user(scope: :account)
      end
    end
    helper_method :current_account

    def current_user
      if user_signed_in?
        @current_user ||= env['warden'].user(scope: :user)
      end
    end
    helper_method :current_user

    def user_signed_in?
      env['warden'].authenticated?(:user)
    end
    helper_method :user_signed_in?

    def authenticate_user!
      unless user_signed_in?
        flash[:notice] = 'Please sign in.'
        redirect_to '/sign_in'
      end
    end

  end
end

app/controllers/subscribem/dashboard_controller.rb
require_dependency "subscribem/application_controller"

module Subscribem
  class DashboardController < ApplicationController
  end
end

app/helpers/subscribem/account/dashboard_helper.rb
module Subscribem
  module Account::DashboardHelper
  end
end

app/helpers/subscribem/account/sessions_helper.rb
module Subscribem
  module Account::SessionsHelper
  end
end

app/helpers/subscribem/accounts_helper.rb
module Subscribem
  module AccountsHelper
  end
end

app/helpers/subscribem/application_helper.rb
module Subscribem
  module ApplicationHelper
  end
end

app/helpers/subscribem/dashboard_helper.rb
module Subscribem
  module DashboardHelper
  end
end

app/views/layouts/subscribem/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Subscribem</title>
  <%= stylesheet_link_tag    "subscribem/application", media: "all" %>
  <%= javascript_include_tag "subscribem/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |k, v| %>
  <div class='flash <%= k %>'><%= v %></div>
<% end %>

<% if user_signed_in? %>
  Signed in as <%= current_user.email %>
<% end %>

<%= yield %>

</body>
</html>

app/views/subscribem/account/dashboard/index.html.erb
Your account's dashboard. Coming soon.

app/views/subscribem/accounts/new.html.erb
<h2>Sign Up</h2>
<%= form_for @account do |account| %>
  <%= account.error_messages %>
  <p>
    <%= account.label :name %><br>
    <%= account.text_field :name %>
  </p>
  <p>
    <%= account.label :subdomain %><br>
    <%= account.text_field :subdomain %>
  </p>
  <%= account.fields_for :owner do |owner| %>
    <p>
      <%= owner.label :email %><br>
      <%= owner.text_field :email %>
    </p>
    <p>
      <%= owner.label :password %><br>
      <%= owner.text_field :password %>
    </p>
    <p>
      <%= owner.label :password_confirmation %><br>
      <%= owner.text_field :password_confirmation %>
    </p>
  <% end %>
  <%= account.submit %>
<% end %>

app/views/subscribem/dashboard/index.html.erb
<%= link_to 'Account Sign Up', sign_up_path %>